# Spelling Words

# 3 Letter Words
threeLetters = (
    'bye',
    'sad',
    'cry',
    'pig',
    'bat',
    'rat',
    'bog',
    'toe',
    'ink',
    'eye', 
    'cat',
    'sit',
    'yes',
    'bad',
    'hat', 
    'eat',
    'pet',
    'net',
    'zip',
    'kid',
) 

# 4 Letter Words
fourLetters = (
    'busy',
    'band',
    'band',
    'able',
    'bark',
    'barn',
    'chop',
    'coat',
    'cone',
    'date',
    'desk',
    'duck',
    'farm',
    'fire',
    'grow',
    'home',
    'jump',
    'kite',
    'lift',
    'leaf'
)

# 5 Letter Words
fiveLetters = (
    'build',
    'early',
    'earth',
    'fruit',
    'group',
    'guard',
    'guide',
    'heard',
    'heart',
    'learn',
    'often',
    'reign',
    'woman',
    'women',
    'eight',
    'bacon',
    'candy',
    'dream',
    'happy',
    'plate',
    'scale',
    'stick',

)

# 6 Letter Words
sixLetters = (
    'actual',
    'answer',
    'appear',
    'arrive',
    'breath',
    'caught', 
    'centre', 
    'circle', 
    'decide', 
    'enough', 
    'famous', 
    'height', 
    'island', 
    'length', 
    'minute', 
    'notice', 
    'recent',
    'weight',
    'eighth',
    'though'

)

# 7 Letter Words
sevenLetters = (
    'address',
    'believe',
    'bicycle',
    'breathe',
    'century', 
    'certain', 
    'extreme', 
    'grammar', 
    'history', 
    'imagine', 
    'library', 
    'mention', 
    'natural', 
    'naughty', 
    'perhaps', 
    'popular', 
    'promise', 
    'purpose', 
    'quarter', 
    'regular', 
    'special', 
    'strange', 
    'suppose', 
    'thought', 
    'through', 
    'various', 
    

)

# 8 Letter Words
eightLetters = (
    'accident',
    'actually',
    'business',
    'calendar',
    'complete', 
    'consider', 
    'continue', 
    'describe', 
    'exercise', 
    'February', 
    'increase', 
    'interest', 
    'material', 
    'medicine', 
    'opposite', 
    'ordinary', 
    'peculiar', 
    'position', 
    'possible', 
    'potatoes', 
    'pressure', 
    'probably', 
    'question', 
    'remember', 
    'sentence', 
    'separate', 
    'straight', 
    'strength', 
    'surprise',
    'forwards',
    'occasion',
    'although'
)

# 9 Letter Words
nineLetters = (
    'different', 
    'difficult', 
    'disappear', 
    'favourite', 
    'important', 
    'knowledge', 
    'therefore',
    'anonymous',
    'exception',
    'guarantee',
    'happiness',
    'excellent',
    'necessary',
    'influence',
    'marketing',
    'agreement',
    'advantage',
    'intention',
    'permanent'


)

# 10 or more Letter Words
tenLetters = (
    'accidentally',
    'experience', 
    'experiment',  
    'particular',  
    'possession', 
    'occasionally', 
    'difficulty',
    'confidence',
    'friendship',
    'generation',
    'blackberry',
    'background',
    'babysitter',
    'commitment',
    'appearance',
    'accomplish',
    'gracefully',
    'industrial',
    'impossible'
)


audioDict = {
    # 3 Letter Words
    'bye': 'static/audio/bye.mp3',
    'sad': 'static/audio/sad.mp3',
    'cry': 'static/audio/cry.mp3',
    'pig': 'static/audio/pig.mp3',
    'bat': 'static/audio/bat.mp3',
    'rat': 'static/audio/rat.mp3',
    'bog': 'static/audio/bog.mp3',
    'toe': 'static/audio/toe.mp3',
    'ink': 'static/audio/ink.mp3',
    'eye': 'static/audio/eye.mp3',
    'cat': 'static/audio/cat.mp3',
    'sit': 'static/audio/sit.mp3',
    'yes': 'static/audio/yes.mp3',
    'bad': 'static/audio/bad.mp3',
    'hat': 'static/audio/hat.mp3',
    'eat': 'static/audio/eat.mp3',
    'pet': 'static/audio/pet.mp3',
    'net': 'static/audio/net.mp3',
    'zip': 'static/audio/zip.mp3',
    'kid': 'static/audio/kid.mp3',

    # 4 Letter Words
    'busy': 'static/audio/busy.mp3',
    'band': 'static/audio/band.mp3',
    'able': 'static/audio/able.mp3',
    'bark': 'static/audio/bark.mp3',
    'barn': 'static/audio/barn.mp3',
    'chop': 'static/audio/chop.mp3',
    'coat': 'static/audio/coat.mp3',
    'cone': 'static/audio/cone.mp3',
    'date': 'static/audio/date.mp3',
    'desk': 'static/audio/desk.mp3',
    'duck': 'static/audio/duck.mp3',
    'farm': 'static/audio/farm.mp3',
    'fire': 'static/audio/fire.mp3',
    'grow': 'static/audio/grow.mp3',
    'home': 'static/audio/home.mp3',
    'jump': 'static/audio/jump.mp3',
    'kite': 'static/audio/kite.mp3',
    'lift': 'static/audio/lift.mp3',
    'leaf': 'static/audio/leaf.mp3',

    # 5 Letter Words
    'build': None,
    'early': None,
    'earth': None,
    'fruit': None,
    'group': None,
    'guard': None,
    'guide': None,
    'heard': None,
    'heart': None,
    'learn': None,
    'often': None,
    'reign': None,
    'woman': None,
    'women': None,
    'eight': None,
    'bacon': None,
    'candy': None,
    'dream': None,
    'happy': None,
    'plate': None,
    'scale': None,
    'stick': None,

    # 6 Letter Words
    'actual': None,
    'answer': None,
    'appear': None,
    'arrive': None,
    'breath': None,
    'caught': None,
    'centre': None,
    'circle': None,
    'decide': None, 
    'enough': None,
    'famous': None, 
    'height': None,
    'island': None,
    'length': None,
    'minute': None,
    'notice': None,
    'recent': None,
    'weight': None,
    'eighth': None,
    'though': None,

    # 7 Letter Words
    'address': None,
    'believe': None,
    'bicycle': None,
    'breathe': None,
    'century': None,
    'certain': None,
    'extreme': None, 
    'grammar': None,
    'history': None,
    'imagine': None,
    'library': None,
    'mention': None,
    'natural': None,
    'naughty': None,
    'perhaps': None,
    'popular': None,
    'promise': None,
    'purpose': None,
    'quarter': None,
    'regular': None,
    'special': None,
    'strange': None,
    'suppose': None,
    'thought': None,
    'through': None,
    'various': None,
        
    # 8 Letter Words
    'accident': None,
    'actually': None,
    'business': None,
    'calendar': None,
    'complete': None,
    'consider': None,
    'continue': None,
    'describe': None,
    'exercise': None,
    'February': None,
    'increase': None,
    'interest': None,
    'material': None,
    'medicine': None,
    'opposite': None,
    'ordinary': None,
    'peculiar': None,
    'position': None,
    'possible': None,
    'potatoes': None,
    'pressure': None,
    'probably': None,
    'question': None,
    'remember': None,
    'sentence': None,
    'separate': None,
    'straight': None,
    'strength': None,
    'surprise': None,
    'forwards': None,
    'occasion': None,
    'although': None,

    # 9 Letter Words
    'different': None, 
    'difficult': None,
    'disappear': None,
    'favourite': None,
    'important': None,
    'knowledge': None,
    'therefore': None,
    'anonymous': None,
    'exception': None,
    'guarantee': None,
    'happiness': None,
    'excellent': None,
    'necessary': None,
    'influence': None,
    'marketing': None,
    'agreement': None,
    'advantage': None,
    'intention': None,
    'permanent': None,

    # 10 or more Letter Words
    'accidentally': None,
    'experience': None,
    'experiment': None,
    'particular': None,
    'possession': None,
    'occasionally': None,
    'difficulty': None,
    'confidence': None,
    'friendship': None,
    'generation': None,
    'blackberry': None,
    'background': None,
    'babysitter': None,
    'commitment': None,
    'appearance': None,
    'accomplish': None,
    'gracefully': None,
    'industrial': None,
    'impossible': None,
}